import BookCall from "@/components/BookCall";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Loading from "@/components/Loading";
import { theme } from "@/theme/antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "./index.css";

export const metadata: Metadata = {
  title: "Welcome to B2B LeadBazz",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={theme}>
      <html lang="en" className="scroll-smooth">
        <body className={`${poppins.className} antialiased relative`}>
          <AntdRegistry>
            <Toaster />
            <Suspense fallback={<Loading />}>
              <Header />
              <BookCall />
              {children}
              <Footer />
            </Suspense>
          </AntdRegistry>
        </body>
      </html>
    </ConfigProvider>
  );
}
